### ISSUE TITLE
CPU 100% on Mac OS 10.10.3 (14D131)

### ISSUE THREAD

**Issue by xcv58** [mattfidler/tabbar-ruler.el#15]
I have the issue, when I comment my line of ```init.el``` to ```require``` ```tabbar-ruler```, the CPU usage drop from more than ```100%``` to less than ```10%```.

This is my Emacs config:
https://github.com/xcv58/Emacs_config/commit/b21ceb99caeb3df32d7db1fce57eb0dfa12be711

My laptop is: 
MacBook Pro (Retina, 13-inch, Early 2015)
Operating System: Mac OS 10.10.3 (14D131)
GNU Emacs 25.0.50.36 (x86_64-apple-darwin14.3.0, NS appkit-1347.57 Version 10.10.3 (Build 14D131)) of 2015-04-13 on xcv58

I build Emacs everyday from https://github.com/emacs-mirror/emacs
My Emacs version is: GNU Emacs 25.0.50.36 (x86_64-apple-darwin14.3.0, NS appkit-1347.57 Version 10.10.3 (Build 14D131)) of 2015-04-13 on xcv58

**Comment by mlf176f2** [comment]
Try

```lisp
(setq tabbar-ruler-movement-timer-dealy 1000000)
```

**Comment by mlf176f2** [comment]
Duplicate as Issue #10

**Comment by xcv58** [comment]
The 
```elisp
(setq tabbar-ruler-movement-timer-dealy 1000000)
```
doesn't work.

CPU usage is still above 100%

**Comment by mlf176f2** [comment]
I don't know what is causing the problem then.

**Comment by rocky-jaiswal** [comment]
From what I saw, tabbar-ruler does this in emacs-24.4. In emacs 24.4 desktop mode is enabled by default. The way tabs are cached in 24.4, causes tabbar-ruler to fail and retry which causes 100% CPU. Have a look at -
https://bitbucket.org/bamanzi/dotemacs-elite/issue/24/tabbar-ruler-not-work-in-emacs-244-keep

**Comment by mlf176f2** [comment]
Great I will apply a patch Monday or sooner

**Comment by rocky-jaiswal** [comment]
Thanks :bow:

**Comment by mlf176f2** [comment]
This should be fixed.

**Comment by xcv58** [comment]
I tried this, it works!

Thank you very much, @mlf176f2 @rocky-jaiswal

**Comment by mdirik** [comment]
@mlf176f2 I'm not sure if it's the same issue but tabbar-ruler still causes very high CPU usage in X process in my machine. I'm using Emacs 24.4 on Debian 8.0, tabbar and tabbar-ruler are in their latest from git revisions. I've tried `(setq tabbar-ruler-movement-timer-dealy 1000000)`  and `(setq tabbar-use-images nil)` workarounds to no avail.

I invocate tabbar-ruler simply with:
```
(require 'tabbar-ruler)
```

**Comment by cjun714** [comment]
I have installed tabbar-ruler-20150428.611 on Ubuntu 14.04, emacs 24.4, this version includes #15 patch, but CPU cost issue still exist.
In Desktop will cost 60-70% CPU usage, emacs -nw will cost 100% CPU usage.
(setq tabbar-ruler-movement-timer-dealy 1000000) also can't solve the issue.

**Comment by mlf176f2** [comment]
I don't know what the issue is...

**Comment by mdirik** [comment]
On May 1, 2015 5:12 PM, "Matthew Fidler" <notifications@github.com> wrote:
>
> I don't know what the issue is...

Any idea on how we can help you troubleshoot it?

>
>
> On Wed, Apr 29, 2015, 12:29 AM cjun714 <notifications@github.com> wrote:
>
> > I have installed tabbar-ruler-20150428.611 on Ubuntu 14.04, emacs 24.4,
> > this version includes #15
> > <https://github.com/mlf176f2/tabbar-ruler.el/issues/15> patch, but CPU
>
> > cost issue still exist.
> > In Desktop will cost 60-70% CPU usage, emacs -nw will cost 100% CPU
usage.
> > (setq tabbar-ruler-movement-timer-dealy 1000000) also can't solve the
> > issue.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
https://github.com/mlf176f2/tabbar-ruler.el/issues/15#issuecomment-97311017>

**Comment by mattfidler** [comment]
Still having this issue.

**Comment by rocky-jaiswal** [comment]
Did you try the latest version, I am using tabbar-ruler right now and its fine for me (on Linux though).

**Comment by mattfidler** [comment]
I don't have the issue.  But others do.  See Issue #28

**Comment by mattfidler** [comment]
I'll close it for now.
